# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimention', models.CharField(default='г.', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('eatEnable', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10000)),
                ('instruction', models.CharField(default='', max_length=10000)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('products', models.ManyToManyField(blank=True, default=None, to='plan.ProductPortion')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.ProductType'),
        ),
    ]
