# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 7, 7, 16, 34, 46, 156467))),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EatPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=100000, null=True)),
                ('subText', models.TextField(blank=True, max_length=100000, null=True)),
                ('appendText', models.TextField(blank=True, max_length=100000, null=True)),
                ('caption', models.TextField(blank=True, max_length=100000, null=True)),
                ('pageName', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimention', models.CharField(default='г.', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('cnt', models.IntegerField(default=1)),
                ('dt', models.FloatField(default=3)),
                ('water', models.FloatField(default=0)),
                ('remain', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10000)),
                ('instruction', models.CharField(default='', max_length=10000)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('eatEnable', models.IntegerField(default=0)),
                ('access', models.BooleanField(default=True)),
                ('remain', models.FloatField(default=0)),
                ('products', models.ManyToManyField(blank=True, default=None, to='plan.ProductPortion')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('tm', models.TimeField(default=datetime.datetime(2017, 7, 7, 16, 34, 46, 155467))),
                ('eatPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.EatPart')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RemainPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime(2017, 7, 7, 16, 34, 46, 140956))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(to='plan.RemainPortion'),
        ),
        migrations.AddField(
            model_name='product',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.ProductType'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='rParts',
            field=models.ManyToManyField(to='plan.RecipePart'),
        ),
    ]
