# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 2, 12, 43, 17, 360797))),
            ],
        ),
        migrations.CreateModel(
            name='EatPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.FloatField(default=0)),
                ('tm', models.TimeField(default=datetime.datetime(2017, 6, 2, 12, 43, 17, 359295))),
                ('eatPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.EatPart')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='eatEnable',
        ),
        migrations.AddField(
            model_name='recipe',
            name='access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='eatEnable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipepart',
            name='recipes',
            field=models.ManyToManyField(to='plan.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='rParts',
            field=models.ManyToManyField(to='plan.RecipePart'),
        ),
    ]
