# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170602_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 3, 12, 30, 4, 89558))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='dt',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 12, 30, 4, 90058)),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 12, 30, 4, 98065)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 3, 12, 30, 4, 95562)),
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(to='plan.RemainPortion'),
        ),
    ]
