# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170707_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 19, 37, 30, 113850)),
        ),
        migrations.AlterField(
            model_name='productportion',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 7, 7, 19, 37, 30, 112849)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 19, 37, 30, 107845)),
        ),
    ]
