# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170707_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inBigSpoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inGlass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inSmallSpoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 21, 11, 13, 256221)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 7, 7, 21, 11, 13, 255721)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 21, 11, 13, 249651)),
        ),
    ]
