# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170707_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimention',
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 21, 26, 41, 429684)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 7, 7, 21, 26, 41, 429183)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 21, 26, 41, 423199)),
        ),
    ]
