# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-03 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170603_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 12, 54, 25, 4872)),
        ),
        migrations.AlterField(
            model_name='product',
            name='dt',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 12, 54, 24, 999869)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 3, 12, 54, 25, 3370)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 12, 54, 24, 999368)),
        ),
    ]
