# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-22 20:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20170722_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portionCnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 23, 49, 5, 271622)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 7, 22, 23, 49, 5, 271121)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 23, 49, 5, 265118)),
        ),
    ]
