# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-22 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170722_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 0, 17, 7, 110892)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plan.RecipeType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 7, 23, 0, 17, 7, 107890)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 0, 17, 7, 79869)),
        ),
    ]
