# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170614_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dt',
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 21, 13, 38, 397144)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 14, 21, 13, 38, 396048)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 21, 13, 38, 392045)),
        ),
    ]
