# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20170614_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dt',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 21, 14, 3, 844092)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 14, 21, 14, 3, 840090)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 21, 14, 3, 836090)),
        ),
    ]
