# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20170614_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 21, 39, 35, 766215)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 15, 21, 39, 35, 764713)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 21, 39, 35, 758709)),
        ),
    ]
