# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20170616_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepart',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipepart',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plan.Recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 16, 22, 20, 16, 434520)),
        ),
        migrations.AlterField(
            model_name='recipepart',
            name='tm',
            field=models.TimeField(default=datetime.datetime(2017, 6, 16, 22, 20, 16, 434019)),
        ),
        migrations.AlterField(
            model_name='remainportion',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 16, 22, 20, 16, 429516)),
        ),
    ]
